version: "2.1"

services:

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    image: piggymetrics-config:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: piggymetrics-registry:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: piggymetrics-gateway:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    image: piggymetrics-auth-service:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    image: my-mongo-image:latest
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    image: piggymetrics-account-service:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-mongodb:
    image: my-mongo-image:latest
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    image: piggymetrics-statistics-service:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-mongodb:
    image: my-mongo-image:latest
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    image: piggymetrics-notification-service:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-mongodb:
    image: my-mongo-image:latest
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    image: piggymetrics-monitoring:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    image: piggymetrics-turbine-stream-service:latest
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"

networks:
  default:
    external:
      name: piggymetrics-net
